-- Manna word bank seed — 180+ Biblical 5-letter words with scripture references.
-- Idempotent: ON CONFLICT (word) DO NOTHING.
INSERT INTO manna_words (word, scripture_reference, scripture_text, created_at) VALUES
  ('GRACE', 'Ephesians 2:8', 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', NOW()),
  ('FAITH', 'Hebrews 11:1', 'Now faith is confidence in what we hope for and assurance about what we do not see.', NOW()),
  ('PEACE', 'John 14:27', 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.', NOW()),
  ('ABIDE', 'John 15:4', 'Abide in me, and I in you. As the branch cannot bear fruit by itself, unless it abides in the vine, neither can you, unless you abide in me.', NOW()),
  ('ARISE', 'Isaiah 60:1', 'Arise, shine, for your light has come, and the glory of the LORD rises upon you.', NOW()),
  ('BLESS', 'Numbers 6:24', 'The LORD bless you and keep you.', NOW()),
  ('BREAD', 'John 6:35', 'Then Jesus declared, I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.', NOW()),
  ('CROSS', 'Galatians 6:14', 'May I never boast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.', NOW()),
  ('CROWN', 'Revelation 2:10', 'Be faithful, even to the point of death, and I will give you life as your victor''s crown.', NOW()),
  ('DWELL', 'Psalm 23:6', 'Surely goodness and love will follow me all the days of my life, and I will dwell in the house of the LORD forever.', NOW()),
  ('EARTH', 'Psalm 24:1', 'The earth is the LORD''s, and everything in it, the world, and all who live in it.', NOW()),
  ('EGYPT', 'Exodus 20:2', 'I am the LORD your God, who brought you out of Egypt, out of the land of slavery.', NOW()),
  ('EXILE', 'Jeremiah 29:11', 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.', NOW()),
  ('FLESH', 'John 1:14', 'The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.', NOW()),
  ('FLOOD', 'Genesis 9:11', 'I establish my covenant with you: Never again will all life be destroyed by the waters of a flood; never again will there be a flood to destroy the earth.', NOW()),
  ('GLORY', 'Romans 8:18', 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.', NOW()),
  ('GROAN', 'Romans 8:26', 'In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.', NOW()),
  ('HEART', 'Proverbs 4:23', 'Above all else, guard your heart, for everything you do flows from it.', NOW()),
  ('HOSEA', 'Hosea 6:6', 'For I desire mercy, not sacrifice, and acknowledgment of God rather than burnt offerings.', NOW()),
  ('JUDAH', 'Genesis 49:10', 'The scepter will not depart from Judah, nor the ruler''s staff from between his feet, until he to whom it belongs shall come.', NOW()),
  ('JUDAS', 'Matthew 26:25', 'Then Judas, the one who would betray him, said, Surely you don''t mean me, Rabbi? Jesus answered, You have said so.', NOW()),
  ('LAMBS', 'Isaiah 40:11', 'He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart.', NOW()),
  ('LIGHT', 'John 8:12', 'When Jesus spoke again to the people, he said, I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.', NOW()),
  ('LIONS', 'Daniel 6:22', 'My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found innocent in his sight.', NOW()),
  ('MANNA', 'Exodus 16:15', 'When the Israelites saw it, they said to each other, What is it? For they did not know what it was. Moses said to them, It is the bread the LORD has given you to eat.', NOW()),
  ('MERCY', 'Lamentations 3:22', 'Because of the LORD''s great love we are not consumed, for his compassions never fail.', NOW()),
  ('MOSES', 'Deuteronomy 34:10', 'Since then, no prophet has risen in Israel like Moses, whom the LORD knew face to face.', NOW()),
  ('MOUNT', 'Isaiah 2:3', 'Many peoples will come and say, Come, let us go up to the mountain of the LORD, to the temple of the God of Jacob.', NOW()),
  ('MYRRH', 'Matthew 2:11', 'On coming to the house, they saw the child with his mother Mary, and they bowed down and worshiped him. Then they opened their treasures and presented him with gifts of gold, frankincense and myrrh.', NOW()),
  ('OMEGA', 'Revelation 22:13', 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.', NOW()),
  ('PETER', 'Matthew 16:18', 'And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.', NOW()),
  ('PLEAD', 'Isaiah 1:18', 'Come now, let us settle the matter, says the LORD. Though your sins are like scarlet, they shall be as white as snow.', NOW()),
  ('PRAYS', 'Romans 8:34', 'Who then is the one who condemns? No one. Christ Jesus who died — more than that, who was raised to life — is at the right hand of God and is also interceding for us.', NOW()),
  ('PSALM', 'Psalm 119:105', 'Your word is a lamp for my feet, a light on my path.', NOW()),
  ('QUEEN', 'Esther 4:14', 'And who knows but that you have come to your royal position for such a time as this?', NOW()),
  ('RAVEN', '1 Kings 17:6', 'The ravens brought him bread and meat in the morning and bread and meat in the evening, and he drank from the brook.', NOW()),
  ('REIGN', 'Revelation 11:15', 'The kingdom of the world has become the kingdom of our Lord and of his Messiah, and he will reign for ever and ever.', NOW()),
  ('RISEN', 'Matthew 28:6', 'He is not here; he has risen, just as he said. Come and see the place where he lay.', NOW()),
  ('RIVER', 'Revelation 22:1', 'Then the angel showed me the river of the water of life, as clear as crystal, flowing from the throne of God and of the Lamb.', NOW()),
  ('ROCKS', 'Matthew 7:25', 'The rain came down, the streams rose, and the winds blew and beat against that house; yet it did not fall, because it had its foundation on the rock.', NOW()),
  ('SAINT', 'Ephesians 1:1', 'Paul, an apostle of Christ Jesus by the will of God, to God''s holy people in Ephesus, the faithful in Christ Jesus.', NOW()),
  ('SATAN', 'Job 1:7', 'The LORD said to Satan, Where have you come from? Satan answered the LORD, From roaming throughout the earth, going back and forth on it.', NOW()),
  ('SEEKS', 'Matthew 7:8', 'For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.', NOW()),
  ('SERVE', 'Joshua 24:15', 'But as for me and my household, we will serve the LORD.', NOW()),
  ('SHEEP', 'John 10:14', 'I am the good shepherd; I know my sheep and my sheep know me.', NOW()),
  ('SINAI', 'Exodus 19:20', 'The LORD descended to the top of Mount Sinai and called Moses to the top of the mountain. So Moses went up.', NOW()),
  ('SMITE', 'Psalm 121:6', 'The sun will not smite you by day, nor the moon by night.', NOW()),
  ('SOULS', 'Psalm 23:3', 'He refreshes my soul. He guides me along the right paths for his name''s sake.', NOW()),
  ('STAFF', 'Psalm 23:4', 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', NOW()),
  ('STONE', 'Psalm 118:22', 'The stone the builders rejected has become the cornerstone.', NOW()),
  ('STORM', 'Mark 4:39', 'He got up, rebuked the wind and said to the waves, Quiet! Be still! Then the wind died down and it was completely calm.', NOW()),
  ('SWORD', 'Ephesians 6:17', 'Take the helmet of salvation and the sword of the Spirit, which is the word of God.', NOW()),
  ('TABLE', 'Psalm 23:5', 'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.', NOW()),
  ('TEACH', 'Psalm 25:4', 'Show me your ways, LORD, teach me your paths.', NOW()),
  ('TITHE', 'Malachi 3:10', 'Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the LORD Almighty.', NOW()),
  ('TITUS', 'Titus 3:5', 'He saved us, not because of righteous things we had done, but because of his mercy.', NOW()),
  ('TOWER', 'Proverbs 18:10', 'The name of the LORD is a fortified tower; the righteous run to it and are safe.', NOW()),
  ('TRIAL', 'James 1:2', 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.', NOW()),
  ('TRUST', 'Proverbs 3:5', 'Trust in the LORD with all your heart and lean not on your own understanding.', NOW()),
  ('TRUTH', 'John 8:32', 'Then you will know the truth, and the truth will set you free.', NOW()),
  ('UNITE', 'Colossians 3:14', 'And over all these virtues put on love, which binds them all together in perfect unity.', NOW()),
  ('UPPER', 'Mark 14:15', 'He will show you a large room upstairs, furnished and ready. Make preparations for us there.', NOW()),
  ('WATCH', 'Mark 13:37', 'What I say to you, I say to everyone: Watch!', NOW()),
  ('WATER', 'John 4:14', 'But whoever drinks the water I give them will never thirst. Indeed, the water I give them will become in them a spring of water welling up to eternal life.', NOW()),
  ('WHEAT', 'Matthew 13:30', 'Let both grow together until the harvest. At that time I will tell the harvesters: First collect the weeds and tie them in bundles to be burned; then gather the wheat and bring it into my barn.', NOW()),
  ('WRATH', 'Romans 5:9', 'Since we have now been justified by his blood, how much more shall we be saved from God''s wrath through him!', NOW()),
  ('YIELD', 'Romans 6:13', 'Do not offer any part of yourself to sin as an instrument of wickedness, but rather offer yourselves to God as those who have been brought from death to life.', NOW()),
  ('SHOUT', 'Psalm 100:1', 'Shout for joy to the LORD, all the earth.', NOW()),
  ('ABHOR', 'Amos 5:15', 'Hate evil, love good; maintain justice in the courts.', NOW()),
  ('ABOVE', 'Colossians 3:2', 'Set your minds on things above, not on earthly things.', NOW()),
  ('AGAIN', 'John 3:3', 'Jesus replied, Very truly I tell you, no one can see the kingdom of God unless they are born again.', NOW()),
  ('ANGEL', 'Hebrews 13:2', 'Do not forget to show hospitality to strangers, for by so doing some people have shown hospitality to angels without knowing it.', NOW()),
  ('ANGER', 'Ephesians 4:26', 'In your anger do not sin: Do not let the sun go down while you are still angry.', NOW()),
  ('ARMOR', 'Ephesians 6:11', 'Put on the full armor of God, so that you can take your stand against the devil''s schemes.', NOW()),
  ('ASKED', 'Matthew 7:7', 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.', NOW()),
  ('BEGAT', 'Matthew 1:16', 'And Jacob begat Joseph the husband of Mary, of whom was born Jesus, who is called Christ.', NOW()),
  ('BEGAN', 'Genesis 1:1', 'In the beginning God created the heavens and the earth.', NOW()),
  ('BEING', 'Acts 17:28', 'For in him we live and move and have our being. As some of your own poets have said, We are his offspring.', NOW()),
  ('BIBLE', 'Psalm 119:11', 'I have hidden your word in my heart that I might not sin against you.', NOW()),
  ('BIRTH', 'Isaiah 9:6', 'For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.', NOW()),
  ('BLOOD', 'Hebrews 9:22', 'Without the shedding of blood there is no forgiveness.', NOW()),
  ('BONES', 'Ezekiel 37:3', 'He asked me, Son of man, can these bones live? I said, Sovereign LORD, you alone know.', NOW()),
  ('BOUND', 'Matthew 18:18', 'Truly I tell you, whatever you bind on earth will be bound in heaven, and whatever you loose on earth will be loosed in heaven.', NOW()),
  ('CALEB', 'Numbers 14:24', 'But because my servant Caleb has a different spirit and follows me wholeheartedly, I will bring him into the land he went to, and his descendants will inherit it.', NOW()),
  ('CALLS', 'Romans 8:30', 'And those he predestined, he also called; those he called, he also justified; those he justified, he also glorified.', NOW()),
  ('CEDAR', '1 Kings 5:6', 'So give orders that cedars of Lebanon be cut for me. My servants will work with yours, and I will pay you for your servants whatever wages you set.', NOW()),
  ('CHAOS', 'Genesis 1:2', 'Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.', NOW()),
  ('CHILD', 'Matthew 18:3', 'Truly I tell you, unless you change and become like little children, you will never enter the kingdom of heaven.', NOW()),
  ('CHOSE', 'John 15:16', 'You did not choose me, but I chose you and appointed you so that you might go and bear fruit.', NOW()),
  ('CLEAN', 'Psalm 51:10', 'Create in me a clean heart, O God, and renew a right spirit within me.', NOW()),
  ('CLOUD', 'Exodus 13:21', 'By day the LORD went ahead of them in a pillar of cloud to guide them on their way and by night in a pillar of fire to give them light.', NOW()),
  ('COMES', 'Psalm 121:2', 'My help comes from the LORD, the Maker of heaven and earth.', NOW()),
  ('DAILY', 'Matthew 6:11', 'Give us today our daily bread.', NOW()),
  ('DAVID', 'Psalm 51:1', 'Have mercy on me, O God, according to your unfailing love; according to your great compassion blot out my transgressions.', NOW()),
  ('DEATH', 'Romans 6:23', 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.', NOW()),
  ('DOING', 'James 1:22', 'Do not merely listen to the word, and so deceive yourselves. Do what it says.', NOW()),
  ('DOUBT', 'Matthew 14:31', 'Immediately Jesus reached out his hand and caught him. You of little faith, he said, why did you doubt?', NOW()),
  ('DRINK', 'John 7:37', 'On the last and greatest day of the festival, Jesus stood and said in a loud voice, Let anyone who is thirsty come to me and drink.', NOW()),
  ('DROVE', 'John 2:15', 'So he made a whip out of cords, and drove all from the temple courts, both sheep and cattle.', NOW()),
  ('DYING', '2 Corinthians 4:10', 'We always carry around in our body the death of Jesus, so that the life of Jesus may also be revealed in our body.', NOW()),
  ('ELIAS', 'James 5:17', 'Elijah was a human being, even as we are. He prayed earnestly that it would not rain, and it did not rain on the land for three and a half years.', NOW()),
  ('ELDER', '1 Timothy 5:17', 'The elders who direct the affairs of the church well are worthy of double honor, especially those whose work is preaching and teaching.', NOW()),
  ('ENEMY', 'Matthew 5:44', 'But I tell you, love your enemies and pray for those who persecute you.', NOW()),
  ('ENTER', 'Matthew 7:13', 'Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it.', NOW()),
  ('SNARE', 'Psalm 91:3', 'Surely he will save you from the fowler''s snare and from the deadly pestilence.', NOW()),
  ('TARES', 'Matthew 13:25', 'But while everyone was sleeping, his enemy came and sowed weeds among the wheat, and went away.', NOW()),
  ('FALLS', 'Proverbs 24:16', 'For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.', NOW()),
  ('FASTS', 'Isaiah 58:6', 'Is not this the kind of fasting I have chosen: to loose the chains of injustice and untie the cords of the yoke?', NOW()),
  ('FEAST', 'Luke 14:16', 'Jesus replied: A certain man was preparing a great banquet and invited many guests.', NOW()),
  ('FIGHT', '1 Timothy 6:12', 'Fight the good fight of the faith. Take hold of the eternal life to which you were called.', NOW()),
  ('FINDS', 'Proverbs 18:22', 'He who finds a wife finds what is good and receives favor from the LORD.', NOW()),
  ('FIRES', 'Daniel 3:17', 'If we are thrown into the blazing furnace, the God we serve is able to deliver us from it.', NOW()),
  ('FIRST', 'Matthew 6:33', 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', NOW()),
  ('FIXED', 'Luke 16:26', 'And besides all this, between us and you a great chasm has been set in place.', NOW()),
  ('FLAME', 'Acts 2:3', 'They saw what seemed to be tongues of fire that separated and came to rest on each of them.', NOW()),
  ('FLOCK', 'Psalm 77:20', 'You led your people like a flock by the hand of Moses and Aaron.', NOW()),
  ('FORTH', 'Isaiah 55:11', 'So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire.', NOW()),
  ('FOUND', 'Luke 15:24', 'For this son of mine was dead and is alive again; he was lost and is found. So they began to celebrate.', NOW()),
  ('FREED', 'Romans 8:2', 'Because through Christ Jesus the law of the Spirit who gives life has freed you from the law of sin and death.', NOW()),
  ('FRUIT', 'Galatians 5:22', 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.', NOW()),
  ('GATES', 'Psalm 100:4', 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.', NOW()),
  ('GIVEN', 'John 3:16', 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.', NOW()),
  ('GIVES', '2 Corinthians 9:7', 'Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.', NOW()),
  ('GOING', 'John 14:2', 'My Father''s house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you?', NOW()),
  ('GRAIN', 'Psalm 72:16', 'May grain abound throughout the land; on the tops of the hills may it sway. May the crops flourish like Lebanon and thrive like the grass of the field.', NOW()),
  ('GRANT', 'Romans 15:13', 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.', NOW()),
  ('GRAVE', 'Hosea 13:14', 'I will deliver this people from the power of the grave; I will redeem them from death.', NOW()),
  ('GREAT', 'Deuteronomy 7:21', 'Do not be terrified by them, for the LORD your God, who is among you, is a great and awesome God.', NOW()),
  ('GUARD', 'Philippians 4:7', 'And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', NOW()),
  ('GUIDE', 'Psalm 32:8', 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.', NOW()),
  ('HANDS', 'Psalm 24:4', 'The one who has clean hands and a pure heart, who does not trust in an idol or swear by a false name.', NOW()),
  ('HEALS', 'Psalm 147:3', 'He heals the brokenhearted and binds up their wounds.', NOW()),
  ('HEARS', 'Psalm 34:17', 'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.', NOW()),
  ('HELPS', 'Psalm 46:1', 'God is our refuge and strength, an ever-present help in trouble.', NOW()),
  ('HERBS', 'Genesis 1:12', 'The land produced vegetation: plants bearing seed according to their kinds and trees bearing fruit with seed in it according to their kinds. And God saw that it was good.', NOW()),
  ('HOLDS', 'Isaiah 41:10', 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.', NOW()),
  ('HOLLY', 'Isaiah 6:3', 'Holy, holy, holy is the LORD Almighty; the whole earth is full of his glory.', NOW()),
  ('HOMER', 'Leviticus 27:16', 'If a man dedicates to the LORD part of his family land, its value is to be set according to the amount of seed required for it — fifty shekels of silver to a homer of barley seed.', NOW()),
  ('HONOR', 'Proverbs 3:9', 'Honor the LORD with your wealth, with the firstfruits of all your crops.', NOW()),
  ('HEIRS', 'Romans 8:17', 'Now if we are children, then we are heirs — heirs of God and co-heirs with Christ, if indeed we share in his sufferings in order that we may also share in his glory.', NOW()),
  ('HOUSE', 'Psalm 127:1', 'Unless the LORD builds the house, the builders labor in vain.', NOW()),
  ('HUMAN', 'Genesis 1:27', 'So God created mankind in his own image, in the image of God he created them; male and female he created them.', NOW()),
  ('HYMNS', 'Colossians 3:16', 'Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit.', NOW()),
  ('IMAGE', 'Genesis 1:27', 'So God created mankind in his own image, in the image of God he created them.', NOW()),
  ('ISAAC', 'Genesis 22:8', 'Abraham answered, God himself will provide the lamb for the burnt offering, my son. And the two of them went on together.', NOW()),
  ('SOWER', 'Matthew 13:3', 'Then he told them many things in parables, saying: A farmer went out to sow his seed.', NOW()),
  ('JACOB', 'Genesis 28:15', 'I am with you and will watch over you wherever you go, and I will bring you back to this land.', NOW()),
  ('JESUS', 'John 1:1', 'In the beginning was the Word, and the Word was with God, and the Word was God.', NOW()),
  ('JOINS', 'Romans 8:17', 'Now if we are children, then we are heirs — heirs of God and co-heirs with Christ.', NOW()),
  ('JONAH', 'Jonah 2:1', 'From inside the fish Jonah prayed to the LORD his God.', NOW()),
  ('JOYED', 'Habakkuk 3:18', 'Yet I will rejoice in the LORD, I will be joyful in God my Savior.', NOW()),
  ('JUDGE', 'Romans 14:10', 'You, then, why do you judge your brother or sister? Or why do you treat them with contempt? For we will all stand before God''s judgment seat.', NOW()),
  ('KEEPS', 'Proverbs 19:16', 'Whoever keeps commandments keeps their life, but whoever shows contempt for their ways will die.', NOW()),
  ('KNEEL', 'Philippians 2:10', 'That at the name of Jesus every knee should bow, in heaven and on earth and under the earth.', NOW()),
  ('KNELT', 'Ezra 9:5', 'At the evening sacrifice I rose from my self-abasement, with my tunic and cloak torn, and fell on my knees with my hands spread out to the LORD my God.', NOW()),
  ('KNOWN', 'Galatians 4:9', 'But now that you know God — or rather are known by God — how is it that you are turning back to those weak and miserable forces?', NOW()),
  ('LABOR', 'Matthew 11:28', 'Come to me, all you who are weary and burdened, and I will give you rest.', NOW()),
  ('LOFTY', 'Isaiah 57:15', 'For this is what the high and exalted One says — he who lives forever, whose name is holy: I live in a high and holy place, but also with the one who is contrite and lowly in spirit.', NOW()),
  ('LAMPS', 'Matthew 25:4', 'The wise ones, however, took oil in jars along with their lamps.', NOW()),
  ('LANDS', 'Psalm 97:5', 'The mountains melt like wax before the LORD, before the Lord of all the earth.', NOW()),
  ('LEADS', 'Psalm 23:2', 'He makes me lie down in green pastures, he leads me beside quiet waters.', NOW()),
  ('LEARN', 'Matthew 11:29', 'Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.', NOW()),
  ('LEANS', 'Proverbs 3:5', 'Trust in the LORD with all your heart and lean not on your own understanding.', NOW()),
  ('LEAPS', 'Psalm 18:29', 'With your help I can advance against a troop; with my God I can scale a wall.', NOW()),
  ('LIVES', 'John 11:25', 'Jesus said to her, I am the resurrection and the life. The one who believes in me will live, even though they die.', NOW()),
  ('LOGOS', 'John 1:1', 'In the beginning was the Word, and the Word was with God, and the Word was God.', NOW()),
  ('SPARE', 'Romans 8:32', 'He who did not spare his own Son, but gave him up for us all — how will he not also, along with him, graciously give us all things?', NOW()),
  ('LOVES', '1 John 4:8', 'Whoever does not love does not know God, because God is love.', NOW()),
  ('LOWLY', 'Matthew 11:29', 'For I am gentle and lowly in heart, and you will find rest for your souls.', NOW()),
  ('LUSTS', 'Galatians 5:16', 'So I say, walk by the Spirit, and you will not gratify the desires of the flesh.', NOW()),
  ('MARKS', 'Galatians 6:17', 'From now on, let no one cause me trouble, for I bear on my body the marks of Jesus.', NOW()),
  ('ABRAM', 'Genesis 12:1', 'The LORD had said to Abram, Go from your country, your people and your father''s household to the land I will show you.', NOW()),
  ('MEEKS', 'Psalm 37:11', 'But the meek will inherit the land and enjoy peace and prosperity.', NOW()),
  ('MIGHT', 'Deuteronomy 6:5', 'Love the LORD your God with all your heart and with all your soul and with all your strength.', NOW()),
  ('MINDS', 'Romans 12:2', 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', NOW()),
  ('MOREH', 'Genesis 12:6', 'Abram traveled through the land as far as the site of the great tree of Moreh at Shechem.', NOW()),
  ('NAOMI', 'Ruth 1:16', 'But Ruth replied, Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.', NOW()),
  ('NEEDS', 'Philippians 4:19', 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.', NOW()),
  ('NIGHT', 'Psalm 91:5', 'You will not fear the terror of night, nor the arrow that flies by day.', NOW()),
  ('NOAHS', 'Genesis 6:22', 'Noah did everything just as God commanded him.', NOW()),
  ('NOBLE', 'Proverbs 31:10', 'A wife of noble character who can find? She is worth far more than rubies.', NOW()),
  ('NURSE', 'Isaiah 49:15', 'Can a mother forget the baby at her breast and have no compassion on the child she has borne? Though she may forget, I will not forget you!', NOW()),
  ('OBEYS', 'Luke 8:25', 'He commands even the winds and the water, and they obey him.', NOW()),
  ('OFFER', 'Romans 12:1', 'Therefore, I urge you, brothers and sisters, in view of God''s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God.', NOW()),
  ('OLIVE', 'Romans 11:17', 'If some of the branches have been broken off, and you, though a wild olive shoot, have been grafted in among the others and now share in the nourishing sap from the olive root.', NOW()),
  ('ORDER', '1 Corinthians 14:40', 'But everything should be done in a fitting and orderly way.', NOW()),
  ('PAGAN', '1 Corinthians 5:1', 'It is actually reported that there is sexual immorality among you, and of a kind that even pagans do not tolerate.', NOW()),
  ('PAINS', 'Romans 8:22', 'We know that the whole creation has been groaning as in the pains of childbirth right up to the present time.', NOW()),
  ('PALMS', 'John 12:13', 'They took palm branches and went out to meet him, shouting, Hosanna! Blessed is he who comes in the name of the Lord!', NOW()),
  ('PATHS', 'Psalm 23:3', 'He guides me along the right paths for his name''s sake.', NOW()),
  ('PRESS', 'Philippians 3:14', 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.', NOW()),
  ('PLUMB', 'Amos 7:8', 'And the LORD asked me, What do you see, Amos? A plumb line, I replied. Then the Lord said, Look, I am setting a plumb line among my people Israel.', NOW()),
  ('PILOT', 'Psalm 48:14', 'For this God is our God for ever and ever; he will be our guide even to the end.', NOW()),
  ('PLANT', '1 Corinthians 3:6', 'I planted the seed, Apollos watered it, but God has been making it grow.', NOW()),
  ('POWER', 'Acts 1:8', 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.', NOW()),
  ('GODLY', '1 Timothy 4:8', 'For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come.', NOW()),
  ('PRICE', '1 Corinthians 6:20', 'You were bought at a price. Therefore honor God with your bodies.', NOW()),
  ('PRIDE', 'Proverbs 11:2', 'When pride comes, then comes disgrace, but with humility comes wisdom.', NOW()),
  ('PROOF', '2 Timothy 3:16', 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.', NOW()),
  ('PROSE', 'Psalm 150:6', 'Let everything that has breath praise the LORD. Praise the LORD.', NOW()),
  ('PROUD', 'James 4:6', 'But he gives us more grace. That is why Scripture says: God opposes the proud but shows favor to the humble.', NOW()),
  ('PROVE', 'Romans 12:2', 'Then you will be able to test and approve what God''s will is — his good, pleasing and perfect will.', NOW()),
  ('PRUNE', 'John 15:2', 'He cuts off every branch in me that bears no fruit, while every branch that does bear fruit he prunes so that it will be even more fruitful.', NOW()),
  ('PURGE', 'Psalm 51:7', 'Cleanse me with hyssop, and I will be clean; wash me, and I will be whiter than snow.', NOW()),
  ('RAISE', 'John 6:40', 'For my Father''s will is that everyone who looks to the Son and believes in him shall have eternal life, and I will raise them up at the last day.', NOW()),
  ('REACH', 'Philippians 3:14', 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.', NOW()),
  ('READS', 'Revelation 1:3', 'Blessed is the one who reads aloud the words of this prophecy.', NOW()),
  ('READY', 'Matthew 24:44', 'So you also must be ready, because the Son of Man will come at an hour when you do not expect him.', NOW()),
  ('REAPS', 'Galatians 6:7', 'Do not be deceived: God cannot be mocked. A man reaps what he sows.', NOW()),
  ('SCORN', 'Psalm 44:13', 'You have made us the scorn of our neighbors, the derision and mockery of those around us.', NOW()),
  ('ATONE', 'Leviticus 16:30', 'Because on this day atonement will be made for you, to cleanse you. Then, before the LORD, you will be clean from all your sins.', NOW()),
  ('REPAY', 'Romans 12:19', 'Do not take revenge, my dear friends, but leave room for God''s wrath, for it is written: It is mine to avenge; I will repay, says the LORD.', NOW()),
  ('WEEPS', 'Luke 19:41', 'As he approached Jerusalem and saw the city, he wept over it.', NOW()),
  ('RESTS', 'Isaiah 11:2', 'The Spirit of the LORD will rest on him — the Spirit of wisdom and of understanding.', NOW()),
  ('RENEW', 'Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles.', NOW()),
  ('GIFTS', 'Romans 11:29', 'For God''s gifts and his call are irrevocable.', NOW()),
  ('RIGHT', 'Psalm 19:8', 'The precepts of the LORD are right, giving joy to the heart.', NOW()),
  ('ROOTS', 'Colossians 2:7', 'Rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.', NOW()),
  ('ROYAL', '1 Peter 2:9', 'But you are a chosen people, a royal priesthood, a holy nation, God''s special possession.', NOW()),
  ('RULES', 'Psalm 103:19', 'The LORD has established his throne in heaven, and his kingdom rules over all.', NOW()),
  ('SAVED', 'Ephesians 2:8', 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', NOW()),
  ('SEALS', 'Ephesians 4:30', 'And do not grieve the Holy Spirit of God, with whom you were sealed for the day of redemption.', NOW()),
  ('SENDS', 'John 3:17', 'For God did not send his Son into the world to condemn the world, but to save the world through him.', NOW()),
  ('SHEDS', 'Romans 5:5', 'And hope does not put us to shame, because God''s love has been poured out into our hearts through the Holy Spirit.', NOW()),
  ('SHINE', 'Matthew 5:16', 'In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.', NOW()),
  ('SIGNS', 'John 20:30', 'Jesus performed many other signs in the presence of his disciples, which are not recorded in this book.', NOW()),
  ('SIMON', 'Mark 1:17', 'Come, follow me, Jesus said, and I will send you out to fish for people.', NOW()),
  ('SINGS', 'Zephaniah 3:17', 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.', NOW()),
  ('SLEEP', 'Psalm 4:8', 'In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety.', NOW()),
  ('SMALL', 'Zechariah 4:10', 'Who dares despise the day of small things?', NOW()),
  ('SOLID', 'Hebrews 5:14', 'But solid food is for the mature, who by constant use have trained themselves to distinguish good from evil.', NOW()),
  ('SONGS', 'Ephesians 5:19', 'Speaking to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord.', NOW()),
  ('SPEAK', 'Jeremiah 1:7', 'But the LORD said to me, Do not say, I am too young. You must go to everyone I send you to and say whatever I command you.', NOW()),
  ('SPEND', 'Isaiah 55:2', 'Why spend money on what is not bread, and your labor on what does not satisfy?', NOW()),
  ('SPIRE', 'Genesis 11:4', 'Then they said, Come, let us build ourselves a city, with a tower that reaches to the heavens.', NOW()),
  ('SPLIT', 'Exodus 14:21', 'Then Moses stretched out his hand over the sea, and all that night the LORD drove the sea back.', NOW()),
  ('STOOD', 'Acts 7:55', 'But Stephen, full of the Holy Spirit, looked up to heaven and saw the glory of God, and Jesus standing at the right hand of God.', NOW()),
  ('STORE', 'Malachi 3:10', 'Bring the whole tithe into the storehouse, that there may be food in my house.', NOW()),
  ('STRAP', 'Luke 3:16', 'I am not worthy to untie the strap of his sandals.', NOW()),
  ('STRAY', 'Isaiah 53:6', 'We all, like sheep, have gone astray, each of us has turned to our own way.', NOW()),
  ('SWEAR', 'Matthew 5:37', 'All you need to say is simply Yes or No; anything beyond this comes from the evil one.', NOW()),
  ('SWEAT', 'Luke 22:44', 'And being in anguish, he prayed more earnestly, and his sweat was like drops of blood falling to the ground.', NOW()),
  ('TAKEN', 'Isaiah 53:8', 'By oppression and judgment he was taken away. Yet who of his generation protested?', NOW()),
  ('TEARS', 'Revelation 21:4', 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.', NOW()),
  ('THANK', '1 Thessalonians 5:18', 'Give thanks in all circumstances; for this is God''s will for you in Christ Jesus.', NOW()),
  ('THINE', 'Matthew 6:13', 'For yours is the kingdom and the power and the glory forever. Amen.', NOW()),
  ('THORN', '2 Corinthians 12:9', 'But he said to me, My grace is sufficient for you, for my power is made perfect in weakness.', NOW()),
  ('THREE', 'Matthew 28:19', 'Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.', NOW()),
  ('THROW', 'Psalm 55:22', 'Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.', NOW()),
  ('TIDES', 'Psalm 93:4', 'Mightier than the thunder of the great waters, mightier than the breakers of the sea — the LORD on high is mighty.', NOW()),
  ('TOILS', 'Matthew 6:28', 'And why do you worry about clothes? See how the flowers of the field grow. They do not labor or spin.', NOW()),
  ('TORAH', 'Psalm 1:2', 'But whose delight is in the law of the LORD, and who meditates on his law day and night.', NOW()),
  ('TOUCH', 'Mark 5:28', 'Because she thought, If I just touch his clothes, I will be healed.', NOW()),
  ('TOWNS', 'Luke 4:43', 'But he said, I must proclaim the good news of the kingdom of God to the other towns also, because that is why I was sent.', NOW()),
  ('TRAIN', 'Proverbs 22:6', 'Start children off on the way they should go, and even when they are old they will not turn from it.', NOW()),
  ('TRIBE', 'Revelation 5:5', 'See, the Lion of the tribe of Judah, the Root of David, has triumphed.', NOW()),
  ('TRIES', 'Psalm 17:3', 'Though you probe my heart, though you examine me at night and test me, you will find that I have planned no evil.', NOW()),
  ('TYING', 'Mark 11:2', 'Go to the village ahead of you, and just as you enter it, you will find a colt tied there.', NOW()),
  ('UNION', 'Ephesians 4:3', 'Make every effort to keep the unity of the Spirit through the bond of peace.', NOW()),
  ('UNITY', 'Psalm 133:1', 'How good and pleasant it is when God''s people live together in unity!', NOW()),
  ('UNTIL', 'Philippians 1:6', 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.', NOW()),
  ('OATHS', 'Hebrews 6:17', 'Because God wanted to make the unchanging nature of his purpose very clear to the heirs of what was promised, he confirmed it with an oath.', NOW()),
  ('VALID', 'John 8:17', 'In your own Law it is written that the testimony of two witnesses is true.', NOW()),
  ('VALOR', 'Joshua 1:9', 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged.', NOW()),
  ('VERSE', 'Psalm 119:11', 'I have hidden your word in my heart that I might not sin against you.', NOW()),
  ('VEXED', 'Psalm 6:3', 'My soul is in deep anguish. How long, LORD, how long?', NOW()),
  ('VINES', 'John 15:5', 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.', NOW()),
  ('VOICE', 'John 10:27', 'My sheep listen to my voice; I know them, and they follow me.', NOW()),
  ('VOWED', 'Numbers 30:2', 'When a man makes a vow to the LORD or takes an oath to obligate himself by a pledge, he must not break his word.', NOW()),
  ('WALKS', 'Micah 6:8', 'And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.', NOW()),
  ('WALLS', 'Nehemiah 4:6', 'So we rebuilt the wall till all of it reached half its height, for the people worked with all their heart.', NOW()),
  ('WANTS', '1 Timothy 2:4', 'Who wants all people to be saved and to come to a knowledge of the truth.', NOW()),
  ('WASTE', 'Isaiah 58:12', 'Your people will rebuild the ancient ruins and will raise up the age-old foundations.', NOW()),
  ('WAVES', 'Matthew 14:29', 'Then Peter got down out of the boat, walked on the water and came toward Jesus.', NOW()),
  ('WEARS', 'Colossians 3:12', 'Therefore, as God''s chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.', NOW()),
  ('WEARY', 'Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.', NOW()),
  ('WELLS', 'Isaiah 12:3', 'With joy you will draw water from the wells of salvation.', NOW()),
  ('WHOLE', 'Deuteronomy 6:5', 'Love the LORD your God with all your heart and with all your soul and with all your strength.', NOW()),
  ('WILLS', 'Matthew 6:10', 'Your kingdom come, your will be done, on earth as it is in heaven.', NOW()),
  ('WINDS', 'Psalm 104:4', 'He makes winds his messengers, flames of fire his servants.', NOW()),
  ('WINGS', 'Psalm 91:4', 'He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart.', NOW()),
  ('WINES', 'John 2:10', 'And he said to him, Everyone serves the good wine first, and when people have drunk freely, then the poor wine. But you have kept the good wine until now.', NOW()),
  ('WISER', 'Proverbs 9:9', 'Instruct the wise and they will be wiser still; teach the righteous and they will add to their learning.', NOW()),
  ('WITTY', 'Proverbs 8:12', 'I, wisdom, dwell together with prudence; I possess knowledge and discretion.', NOW()),
  ('WOMEN', 'Luke 8:3', 'And Joanna the wife of Chuza, the manager of Herod''s household; Susanna; and many others. These women were helping to support them out of their own means.', NOW()),
  ('WORDS', 'Psalm 19:14', 'May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer.', NOW()),
  ('WORKS', 'Ephesians 2:10', 'For we are God''s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.', NOW()),
  ('WORLD', 'John 3:16', 'For God so loved the world that he gave his one and only Son.', NOW()),
  ('WORRY', 'Matthew 6:34', 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.', NOW()),
  ('WORTH', 'Romans 8:18', 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.', NOW()),
  ('WOUND', 'Isaiah 53:5', 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.', NOW()),
  ('WRITE', 'Habakkuk 2:2', 'Then the LORD replied: Write down the revelation and make it plain on tablets so that a herald may run with it.', NOW()),
  ('YOUNG', 'Psalm 119:9', 'How can a young person stay on the path of purity? By living according to your word.', NOW()),
  ('YOURS', 'Psalm 24:1', 'The earth is the LORD''s, and everything in it.', NOW()),
  ('SOBER', '1 Peter 5:8', 'Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour.', NOW()),
  ('ZEALS', 'Numbers 25:13', 'He and his descendants will have a covenant of a lasting priesthood, because he was zealous for the honor of his God.', NOW())
ON CONFLICT (word) DO NOTHING;
