-- Manna word bank seed — Biblical 5-letter words with scripture references.
-- Idempotent: ON CONFLICT (word) DO NOTHING.
-- Only entries where the target word actually appears in the scripture text.
INSERT INTO manna_words (word, scripture_reference, scripture_text, created_at) VALUES
  ('GRACE', 'Ephesians 2:8', 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', NOW()),
  ('FAITH', 'Hebrews 11:1', 'Now faith is confidence in what we hope for and assurance about what we do not see.', NOW()),
  ('PEACE', 'John 14:27', 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.', NOW()),
  ('ABIDE', 'John 15:4', 'Abide in me, and I in you. As the branch cannot bear fruit by itself, unless it abides in the vine, neither can you, unless you abide in me.', NOW()),
  ('ARISE', 'Isaiah 60:1', 'Arise, shine, for your light has come, and the glory of the LORD rises upon you.', NOW()),
  ('BLESS', 'Numbers 6:24', 'The LORD bless you and keep you.', NOW()),
  ('BREAD', 'John 6:35', 'Then Jesus declared, I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.', NOW()),
  ('CROSS', 'Galatians 6:14', 'May I never boast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.', NOW()),
  ('CROWN', 'Revelation 2:10', 'Be faithful, even to the point of death, and I will give you life as your victor''s crown.', NOW()),
  ('DWELL', 'Psalm 23:6', 'Surely goodness and love will follow me all the days of my life, and I will dwell in the house of the LORD forever.', NOW()),
  ('EARTH', 'Psalm 24:1', 'The earth is the LORD''s, and everything in it, the world, and all who live in it.', NOW()),
  ('EGYPT', 'Exodus 20:2', 'I am the LORD your God, who brought you out of Egypt, out of the land of slavery.', NOW()),
  ('EXILE', 'Jeremiah 29:7', 'Also, seek the peace and prosperity of the city to which I have carried you into exile. Pray to the LORD for it.', NOW()),
  ('FLESH', 'John 1:14', 'The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.', NOW()),
  ('FLOOD', 'Genesis 9:11', 'I establish my covenant with you: Never again will all life be destroyed by the waters of a flood; never again will there be a flood to destroy the earth.', NOW()),
  ('GLORY', 'Romans 8:18', 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.', NOW()),
  ('HEART', 'Proverbs 4:23', 'Above all else, guard your heart, for everything you do flows from it.', NOW()),
  ('JUDAH', 'Genesis 49:10', 'The scepter will not depart from Judah, nor the ruler''s staff from between his feet, until he to whom it belongs shall come.', NOW()),
  ('JUDAS', 'Matthew 26:25', 'Then Judas, the one who would betray him, said, Surely you don''t mean me, Rabbi? Jesus answered, You have said so.', NOW()),
  ('LAMBS', 'Isaiah 40:11', 'He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart.', NOW()),
  ('LIGHT', 'John 8:12', 'When Jesus spoke again to the people, he said, I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.', NOW()),
  ('LIONS', 'Daniel 6:22', 'My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found innocent in his sight.', NOW()),
  ('MOSES', 'Deuteronomy 34:10', 'Since then, no prophet has risen in Israel like Moses, whom the LORD knew face to face.', NOW()),
  ('MYRRH', 'Matthew 2:11', 'On coming to the house, they saw the child with his mother Mary, and they bowed down and worshiped him. Then they opened their treasures and presented him with gifts of gold, frankincense and myrrh.', NOW()),
  ('OMEGA', 'Revelation 22:13', 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.', NOW()),
  ('PETER', 'Matthew 16:18', 'And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.', NOW()),
  ('PLEAD', 'Job 9:15', 'Though I were innocent, I could not answer him; I could only plead with my Judge for mercy.', NOW()),
  ('REIGN', 'Revelation 11:15', 'The kingdom of the world has become the kingdom of our Lord and of his Messiah, and he will reign for ever and ever.', NOW()),
  ('RISEN', 'Matthew 28:6', 'He is not here; he has risen, just as he said. Come and see the place where he lay.', NOW()),
  ('RIVER', 'Revelation 22:1', 'Then the angel showed me the river of the water of life, as clear as crystal, flowing from the throne of God and of the Lamb.', NOW()),
  ('SATAN', 'Job 1:7', 'The LORD said to Satan, Where have you come from? Satan answered the LORD, From roaming throughout the earth, going back and forth on it.', NOW()),
  ('SEEKS', 'Matthew 7:8', 'For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.', NOW()),
  ('SERVE', 'Joshua 24:15', 'But as for me and my household, we will serve the LORD.', NOW()),
  ('SHEEP', 'John 10:14', 'I am the good shepherd; I know my sheep and my sheep know me.', NOW()),
  ('SINAI', 'Exodus 19:20', 'The LORD descended to the top of Mount Sinai and called Moses to the top of the mountain. So Moses went up.', NOW()),
  ('SMITE', 'Psalm 121:6', 'The sun will not smite you by day, nor the moon by night.', NOW()),
  ('STAFF', 'Psalm 23:4', 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', NOW()),
  ('STONE', 'Psalm 118:22', 'The stone the builders rejected has become the cornerstone.', NOW()),
  ('SWORD', 'Ephesians 6:17', 'Take the helmet of salvation and the sword of the Spirit, which is the word of God.', NOW()),
  ('TABLE', 'Psalm 23:5', 'You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows.', NOW()),
  ('TEACH', 'Psalm 25:4', 'Show me your ways, LORD, teach me your paths.', NOW()),
  ('TITHE', 'Malachi 3:10', 'Bring the whole tithe into the storehouse, that there may be food in my house. Test me in this, says the LORD Almighty.', NOW()),
  ('TOWER', 'Proverbs 18:10', 'The name of the LORD is a fortified tower; the righteous run to it and are safe.', NOW()),
  ('TRUST', 'Proverbs 3:5', 'Trust in the LORD with all your heart and lean not on your own understanding.', NOW()),
  ('TRUTH', 'John 8:32', 'Then you will know the truth, and the truth will set you free.', NOW()),
  ('WATCH', 'Mark 13:37', 'What I say to you, I say to everyone: Watch!', NOW()),
  ('WATER', 'John 4:14', 'But whoever drinks the water I give them will never thirst. Indeed, the water I give them will become in them a spring of water welling up to eternal life.', NOW()),
  ('WHEAT', 'Matthew 13:30', 'Let both grow together until the harvest. At that time I will tell the harvesters: First collect the weeds and tie them in bundles to be burned; then gather the wheat and bring it into my barn.', NOW()),
  ('WRATH', 'Romans 5:9', 'Since we have now been justified by his blood, how much more shall we be saved from God''s wrath through him!', NOW()),
  ('SHOUT', 'Psalm 100:1', 'Shout for joy to the LORD, all the earth.', NOW()),
  ('ABOVE', 'Colossians 3:2', 'Set your minds on things above, not on earthly things.', NOW()),
  ('AGAIN', 'John 3:3', 'Jesus replied, Very truly I tell you, no one can see the kingdom of God unless they are born again.', NOW()),
  ('ANGER', 'Ephesians 4:26', 'In your anger do not sin: Do not let the sun go down while you are still angry.', NOW()),
  ('ARMOR', 'Ephesians 6:11', 'Put on the full armor of God, so that you can take your stand against the devil''s schemes.', NOW()),
  ('BEGAT', 'Matthew 1:16', 'And Jacob begat Joseph the husband of Mary, of whom was born Jesus, who is called Christ.', NOW()),
  ('BEING', 'Acts 17:28', 'For in him we live and move and have our being. As some of your own poets have said, We are his offspring.', NOW()),
  ('BLOOD', 'Hebrews 9:22', 'Without the shedding of blood there is no forgiveness.', NOW()),
  ('BONES', 'Ezekiel 37:3', 'He asked me, Son of man, can these bones live? I said, Sovereign LORD, you alone know.', NOW()),
  ('BOUND', 'Matthew 18:18', 'Truly I tell you, whatever you bind on earth will be bound in heaven, and whatever you loose on earth will be loosed in heaven.', NOW()),
  ('CALEB', 'Numbers 14:24', 'But because my servant Caleb has a different spirit and follows me wholeheartedly, I will bring him into the land he went to, and his descendants will inherit it.', NOW()),
  ('CHILD', 'Isaiah 9:6', 'For to us a child is born, to us a son is given; and the government shall be upon his shoulder.', NOW()),
  ('CHOSE', 'John 15:16', 'You did not choose me, but I chose you and appointed you so that you might go and bear fruit.', NOW()),
  ('CLEAN', 'Psalm 51:10', 'Create in me a clean heart, O God, and renew a right spirit within me.', NOW()),
  ('CLOUD', 'Exodus 13:21', 'By day the LORD went ahead of them in a pillar of cloud to guide them on their way and by night in a pillar of fire to give them light.', NOW()),
  ('COMES', 'Psalm 121:2', 'My help comes from the LORD, the Maker of heaven and earth.', NOW()),
  ('DAILY', 'Matthew 6:11', 'Give us today our daily bread.', NOW()),
  ('DEATH', 'Romans 6:23', 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.', NOW()),
  ('DOUBT', 'Matthew 14:31', 'Immediately Jesus reached out his hand and caught him. You of little faith, he said, why did you doubt?', NOW()),
  ('DRINK', 'John 7:37', 'On the last and greatest day of the festival, Jesus stood and said in a loud voice, Let anyone who is thirsty come to me and drink.', NOW()),
  ('DROVE', 'John 2:15', 'So he made a whip out of cords, and drove all from the temple courts, both sheep and cattle.', NOW()),
  ('ENTER', 'Matthew 7:13', 'Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it.', NOW()),
  ('SNARE', 'Psalm 91:3', 'Surely he will save you from the fowler''s snare and from the deadly pestilence.', NOW()),
  ('FEAST', 'Isaiah 25:6', 'On this mountain the LORD Almighty will prepare a feast of rich food for all peoples.', NOW()),
  ('FIGHT', '1 Timothy 6:12', 'Fight the good fight of the faith. Take hold of the eternal life to which you were called.', NOW()),
  ('FINDS', 'Proverbs 18:22', 'He who finds a wife finds what is good and receives favor from the LORD.', NOW()),
  ('FIRST', 'Matthew 6:33', 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.', NOW()),
  ('FLAME', 'Hebrews 1:7', 'He makes his angels winds, and his ministers a flame of fire.', NOW()),
  ('FLOCK', 'Psalm 77:20', 'You led your people like a flock by the hand of Moses and Aaron.', NOW()),
  ('FOUND', 'Luke 15:24', 'For this son of mine was dead and is alive again; he was lost and is found. So they began to celebrate.', NOW()),
  ('FREED', 'Romans 8:2', 'Because through Christ Jesus the law of the Spirit who gives life has freed you from the law of sin and death.', NOW()),
  ('FRUIT', 'Galatians 5:22', 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.', NOW()),
  ('GATES', 'Psalm 100:4', 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.', NOW()),
  ('GIVES', 'James 1:5', 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.', NOW()),
  ('GOING', 'John 14:2', 'My Father''s house has many rooms; if that were not so, would I have told you that I am going there to prepare a place for you?', NOW()),
  ('GRAIN', 'Psalm 72:16', 'May grain abound throughout the land; on the tops of the hills may it sway. May the crops flourish like Lebanon and thrive like the grass of the field.', NOW()),
  ('GRAVE', 'Hosea 13:14', 'I will deliver this people from the power of the grave; I will redeem them from death.', NOW()),
  ('GREAT', 'Deuteronomy 7:21', 'Do not be terrified by them, for the LORD your God, who is among you, is a great and awesome God.', NOW()),
  ('GUARD', 'Philippians 4:7', 'And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.', NOW()),
  ('HANDS', 'Psalm 24:4', 'The one who has clean hands and a pure heart, who does not trust in an idol or swear by a false name.', NOW()),
  ('HEALS', 'Psalm 147:3', 'He heals the brokenhearted and binds up their wounds.', NOW()),
  ('HEARS', 'Psalm 34:17', 'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.', NOW()),
  ('HELPS', 'Romans 8:26', 'The Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us.', NOW()),
  ('HOMER', 'Leviticus 27:16', 'If a man dedicates to the LORD part of his family land, its value is to be set according to the amount of seed required for it — fifty shekels of silver to a homer of barley seed.', NOW()),
  ('HONOR', 'Proverbs 3:9', 'Honor the LORD with your wealth, with the firstfruits of all your crops.', NOW()),
  ('HEIRS', 'Romans 8:17', 'Now if we are children, then we are heirs — heirs of God and co-heirs with Christ, if indeed we share in his sufferings in order that we may also share in his glory.', NOW()),
  ('HOUSE', 'Psalm 127:1', 'Unless the LORD builds the house, the builders labor in vain.', NOW()),
  ('HYMNS', 'Colossians 3:16', 'Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit.', NOW()),
  ('IMAGE', 'Genesis 1:27', 'So God created mankind in his own image, in the image of God he created them.', NOW()),
  ('ISAAC', 'Genesis 22:2', 'Then God said, Take your son, your only son, whom you love — Isaac — and go to the region of Moriah.', NOW()),
  ('JACOB', 'Genesis 32:28', 'Then the man said, Your name will no longer be Jacob, but Israel, because you have struggled with God and with humans and have overcome.', NOW()),
  ('JONAH', 'Jonah 2:1', 'From inside the fish Jonah prayed to the LORD his God.', NOW()),
  ('JUDGE', 'Romans 14:10', 'You, then, why do you judge your brother or sister? Or why do you treat them with contempt? For we will all stand before God''s judgment seat.', NOW()),
  ('KEEPS', 'Proverbs 19:16', 'Whoever keeps commandments keeps their life, but whoever shows contempt for their ways will die.', NOW()),
  ('KNEEL', 'Psalm 95:6', 'Come, let us bow down in worship, let us kneel before the LORD our Maker.', NOW()),
  ('KNOWN', 'Galatians 4:9', 'But now that you know God — or rather are known by God — how is it that you are turning back to those weak and miserable forces?', NOW()),
  ('LAMPS', 'Matthew 25:4', 'The wise ones, however, took oil in jars along with their lamps.', NOW()),
  ('LEADS', 'Psalm 23:2', 'He makes me lie down in green pastures, he leads me beside quiet waters.', NOW()),
  ('LEARN', 'Matthew 11:29', 'Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.', NOW()),
  ('LIVES', 'Galatians 2:20', 'I have been crucified with Christ and I no longer live, but Christ lives in me.', NOW()),
  ('SPARE', 'Romans 8:32', 'He who did not spare his own Son, but gave him up for us all — how will he not also, along with him, graciously give us all things?', NOW()),
  ('LOWLY', 'Matthew 11:29', 'For I am gentle and lowly in heart, and you will find rest for your souls.', NOW()),
  ('MARKS', 'Galatians 6:17', 'From now on, let no one cause me trouble, for I bear on my body the marks of Jesus.', NOW()),
  ('ABRAM', 'Genesis 12:1', 'The LORD had said to Abram, Go from your country, your people and your father''s household to the land I will show you.', NOW()),
  ('MIGHT', 'Zechariah 4:6', 'Not by might nor by power, but by my Spirit, says the LORD Almighty.', NOW()),
  ('MOREH', 'Genesis 12:6', 'Abram traveled through the land as far as the site of the great tree of Moreh at Shechem.', NOW()),
  ('NEEDS', 'Philippians 4:19', 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.', NOW()),
  ('NIGHT', 'Psalm 91:5', 'You will not fear the terror of night, nor the arrow that flies by day.', NOW()),
  ('NOBLE', 'Proverbs 31:10', 'A wife of noble character who can find? She is worth far more than rubies.', NOW()),
  ('OFFER', 'Romans 12:1', 'Therefore, I urge you, brothers and sisters, in view of God''s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God.', NOW()),
  ('OLIVE', 'Romans 11:17', 'If some of the branches have been broken off, and you, though a wild olive shoot, have been grafted in among the others and now share in the nourishing sap from the olive root.', NOW()),
  ('PAINS', 'Romans 8:22', 'We know that the whole creation has been groaning as in the pains of childbirth right up to the present time.', NOW()),
  ('PATHS', 'Psalm 23:3', 'He guides me along the right paths for his name''s sake.', NOW()),
  ('PRESS', 'Philippians 3:14', 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.', NOW()),
  ('PLUMB', 'Amos 7:8', 'And the LORD asked me, What do you see, Amos? A plumb line, I replied. Then the Lord said, Look, I am setting a plumb line among my people Israel.', NOW()),
  ('POWER', 'Acts 1:8', 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.', NOW()),
  ('PRICE', '1 Corinthians 6:20', 'You were bought at a price. Therefore honor God with your bodies.', NOW()),
  ('PRIDE', 'Proverbs 11:2', 'When pride comes, then comes disgrace, but with humility comes wisdom.', NOW()),
  ('PROUD', 'James 4:6', 'But he gives us more grace. That is why Scripture says: God opposes the proud but shows favor to the humble.', NOW()),
  ('RAISE', 'John 6:40', 'For my Father''s will is that everyone who looks to the Son and believes in him shall have eternal life, and I will raise them up at the last day.', NOW()),
  ('READS', 'Revelation 1:3', 'Blessed is the one who reads aloud the words of this prophecy.', NOW()),
  ('READY', 'Matthew 24:44', 'So you also must be ready, because the Son of Man will come at an hour when you do not expect him.', NOW()),
  ('REAPS', 'Galatians 6:7', 'Do not be deceived: God cannot be mocked. A man reaps what he sows.', NOW()),
  ('SCORN', 'Psalm 44:13', 'You have made us the scorn of our neighbors, the derision and mockery of those around us.', NOW()),
  ('REPAY', 'Romans 12:19', 'Do not take revenge, my dear friends, but leave room for God''s wrath, for it is written: It is mine to avenge; I will repay, says the LORD.', NOW()),
  ('RENEW', 'Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles.', NOW()),
  ('GIFTS', 'Romans 11:29', 'For God''s gifts and his call are irrevocable.', NOW()),
  ('RIGHT', 'Psalm 19:8', 'The precepts of the LORD are right, giving joy to the heart.', NOW()),
  ('ROYAL', '1 Peter 2:9', 'But you are a chosen people, a royal priesthood, a holy nation, God''s special possession.', NOW()),
  ('RULES', 'Psalm 103:19', 'The LORD has established his throne in heaven, and his kingdom rules over all.', NOW()),
  ('SAVED', 'Ephesians 2:8', 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.', NOW()),
  ('SHINE', 'Matthew 5:16', 'In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.', NOW()),
  ('SIGNS', 'John 20:30', 'Jesus performed many other signs in the presence of his disciples, which are not recorded in this book.', NOW()),
  ('SLEEP', 'Psalm 4:8', 'In peace I will lie down and sleep, for you alone, LORD, make me dwell in safety.', NOW()),
  ('SMALL', 'Zechariah 4:10', 'Who dares despise the day of small things?', NOW()),
  ('SOLID', 'Hebrews 5:14', 'But solid food is for the mature, who by constant use have trained themselves to distinguish good from evil.', NOW()),
  ('SONGS', 'Ephesians 5:19', 'Speaking to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord.', NOW()),
  ('SPEAK', 'Numbers 22:38', 'I must speak only what God puts in my mouth.', NOW()),
  ('SPEND', 'Isaiah 55:2', 'Why spend money on what is not bread, and your labor on what does not satisfy?', NOW()),
  ('STORE', 'Matthew 6:20', 'But store up for yourselves treasures in heaven, where moths and vermin do not destroy, and where thieves do not break in and steal.', NOW()),
  ('STRAP', 'Luke 3:16', 'I am not worthy to untie the strap of his sandals.', NOW()),
  ('SWEAR', 'Matthew 5:34', 'But I tell you, do not swear an oath at all: either by heaven, for it is God''s throne.', NOW()),
  ('SWEAT', 'Luke 22:44', 'And being in anguish, he prayed more earnestly, and his sweat was like drops of blood falling to the ground.', NOW()),
  ('TAKEN', 'Isaiah 53:8', 'By oppression and judgment he was taken away. Yet who of his generation protested?', NOW()),
  ('TEARS', 'Psalm 56:8', 'You have kept count of my tossings; put my tears in your bottle.', NOW()),
  ('THREE', 'Matthew 18:20', 'For where two or three gather in my name, there am I with them.', NOW()),
  ('TOUCH', 'Mark 5:28', 'Because she thought, If I just touch his clothes, I will be healed.', NOW()),
  ('TOWNS', 'Luke 4:43', 'But he said, I must proclaim the good news of the kingdom of God to the other towns also, because that is why I was sent.', NOW()),
  ('TRIBE', 'Revelation 5:5', 'See, the Lion of the tribe of Judah, the Root of David, has triumphed.', NOW()),
  ('UNITY', 'Psalm 133:1', 'How good and pleasant it is when God''s people live together in unity!', NOW()),
  ('UNTIL', 'Philippians 1:6', 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.', NOW()),
  ('VOICE', 'John 10:27', 'My sheep listen to my voice; I know them, and they follow me.', NOW()),
  ('WANTS', '1 Timothy 2:4', 'Who wants all people to be saved and to come to a knowledge of the truth.', NOW()),
  ('WEARY', 'Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.', NOW()),
  ('WELLS', 'Isaiah 12:3', 'With joy you will draw water from the wells of salvation.', NOW()),
  ('WINDS', 'Psalm 104:4', 'He makes winds his messengers, flames of fire his servants.', NOW()),
  ('WINGS', 'Psalm 91:4', 'He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart.', NOW()),
  ('WISER', 'Proverbs 9:9', 'Instruct the wise and they will be wiser still; teach the righteous and they will add to their learning.', NOW()),
  ('WOMEN', 'Luke 8:3', 'And Joanna the wife of Chuza, the manager of Herod''s household; Susanna; and many others. These women were helping to support them out of their own means.', NOW()),
  ('WORDS', 'Psalm 19:14', 'May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer.', NOW()),
  ('WORKS', 'Ephesians 2:10', 'For we are God''s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.', NOW()),
  ('WORLD', 'John 3:16', 'For God so loved the world that he gave his one and only Son.', NOW()),
  ('WORRY', 'Matthew 6:34', 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.', NOW()),
  ('WORTH', 'Romans 8:18', 'I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.', NOW()),
  ('WRITE', 'Habakkuk 2:2', 'Then the LORD replied: Write down the revelation and make it plain on tablets so that a herald may run with it.', NOW()),
  ('YOUNG', 'Psalm 119:9', 'How can a young person stay on the path of purity? By living according to your word.', NOW()),
  ('SOBER', '1 Thessalonians 5:6', 'So then, let us not be like others, who are asleep, but let us be awake and sober.', NOW()),
  ('AARON', 'Exodus 4:14', 'Then the LORD''s anger burned against Moses and he said, What about your brother, Aaron the Levite? I know he can speak well.', NOW()),
  ('ABNER', '2 Samuel 2:8', 'Meanwhile, Abner son of Ner, the commander of Saul''s army, had taken Ish-Bosheth son of Saul and brought him over to Mahanaim.', NOW()),
  ('ACHAN', 'Joshua 7:20', 'Achan replied, It is true! I have sinned against the LORD, the God of Israel. This is what I have done.', NOW()),
  ('ANNAS', 'Luke 3:2', 'During the high-priesthood of Annas and Caiaphas, the word of God came to John son of Zechariah in the wilderness.', NOW()),
  ('ASHER', 'Deuteronomy 33:24', 'About Asher he said: ''Most blessed of sons is Asher; let him be favored by his brothers, and let him bathe his feet in oil.''', NOW()),
  ('CYRUS', 'Isaiah 45:1', 'This is what the LORD says to his anointed, to Cyrus, whose right hand I take hold of to subdue nations before him.', NOW()),
  ('DAGON', '1 Samuel 5:4', 'But the following morning when they rose, there was Dagon, fallen on his face on the ground before the ark of the LORD!', NOW()),
  ('ELIAM', '2 Samuel 23:34', 'Eliphelet son of Ahasbai the Maakathite, Eliam son of Ahithophel the Gilonite.', NOW()),
  ('ENOCH', 'Genesis 5:24', 'Enoch walked faithfully with God; then he was no more, because God took him away.', NOW()),
  ('ETHAN', 'Psalm 89:1', 'A maskil of Ethan the Ezrahite. I will sing of the LORD''s great love forever; with my mouth I will make your faithfulness known through all generations.', NOW()),
  ('FELIX', 'Acts 24:24', 'Several days later Felix came with his wife Drusilla. He sent for Paul and listened to him as he spoke about faith in Christ Jesus.', NOW()),
  ('HAGAR', 'Genesis 21:17', 'God heard the boy crying, and the angel of God called to Hagar from heaven and said to her, What is the matter, Hagar? Do not be afraid.', NOW()),
  ('HEROD', 'Matthew 2:16', 'When Herod realized that he had been outwitted by the Magi, he was furious, and he gave orders to kill all the boys in Bethlehem.', NOW()),
  ('HIRAM', '1 Kings 5:12', 'The LORD gave Solomon wisdom, just as he had promised him. There were peaceful relations between Hiram and Solomon, and the two of them made a treaty.', NOW()),
  ('JABAL', 'Genesis 4:20', 'Adah gave birth to Jabal; he was the father of those who live in tents and raise livestock.', NOW()),
  ('JASON', 'Acts 17:6', 'But when they did not find them, they dragged Jason and some other believers before the city officials, shouting: These men who have caused trouble all over the world have now come here.', NOW()),
  ('JOASH', '2 Kings 12:2', 'Joash did what was right in the eyes of the LORD all the years Jehoiada the priest instructed him.', NOW()),
  ('JUBAL', 'Genesis 4:21', 'His brother''s name was Jubal; he was the father of all who play stringed instruments and pipes.', NOW()),
  ('LABAN', 'Genesis 29:10', 'When Jacob saw Rachel daughter of his uncle Laban, and Laban''s sheep, he went over and rolled the stone away from the mouth of the well.', NOW()),
  ('LYDIA', 'Acts 16:14', 'One of those listening was a woman from the city of Thyatira named Lydia, a dealer in purple cloth. The Lord opened her heart to respond to Paul''s message.', NOW()),
  ('MAMRE', 'Genesis 18:1', 'The LORD appeared to Abraham near the great trees of Mamre while he was sitting at the entrance to his tent in the heat of the day.', NOW()),
  ('MERAB', '1 Samuel 14:49', 'Saul''s sons were Jonathan, Ishvi and Malki-Shua. The name of his older daughter was Merab, and that of the younger was Michal.', NOW()),
  ('MESHA', '2 Kings 3:4', 'Now Mesha king of Moab raised sheep, and he had to pay the king of Israel a tribute of a hundred thousand lambs.', NOW()),
  ('NABAL', '1 Samuel 25:3', 'His name was Nabal and his wife''s name was Abigail. She was an intelligent and beautiful woman, but her husband was surly and mean in his dealings.', NOW()),
  ('PALTI', 'Numbers 13:9', 'From the tribe of Benjamin, Palti son of Raphu.', NOW()),
  ('PEREZ', 'Genesis 38:29', 'But when he drew back his hand, his brother came out, and she said, So this is how you have broken out! And he was named Perez.', NOW()),
  ('RAHAB', 'Hebrews 11:31', 'By faith the prostitute Rahab, because she welcomed the spies, was not killed with those who were disobedient.', NOW()),
  ('REUEL', 'Exodus 2:18', 'When the girls returned to Reuel their father, he asked them, Why have you returned so early today?', NOW()),
  ('REZIN', '2 Kings 15:37', 'In those days the LORD began to send Rezin king of Aram and Pekah son of Remaliah against Judah.', NOW()),
  ('RUFUS', 'Romans 16:13', 'Greet Rufus, chosen in the Lord, and his mother, who has been a mother to me, too.', NOW()),
  ('SARAH', 'Genesis 17:15', 'God also said to Abraham, As for Sarai your wife, you are no longer to call her Sarai; her name will be Sarah.', NOW()),
  ('SARAI', 'Genesis 12:11', 'As he was about to enter Egypt, he said to his wife Sarai, I know what a beautiful woman you are.', NOW()),
  ('TEMAN', 'Habakkuk 3:3', 'God came from Teman, the Holy One from Mount Paran. His glory covered the heavens and his praise filled the earth.', NOW()),
  ('TIMON', 'Acts 6:5', 'This proposal pleased the whole group. They chose Stephen, a man full of faith and of the Holy Spirit; also Philip, Procorus, Nicanor, Timon, Parmenas, and Nicolas.', NOW()),
  ('URIAH', '2 Samuel 11:11', 'Uriah said to David, The ark and Israel and Judah are staying in tents, and my commander Joab and my lord''s men are camped in the open country.', NOW()),
  ('ZIMRI', '1 Kings 16:18', 'When Zimri saw that the city was taken, he went into the citadel of the royal palace and set the palace on fire around him. So he died.', NOW()),
  ('BABEL', 'Genesis 11:9', 'That is why it was called Babel — because there the LORD confused the language of the whole world. From there the LORD scattered them over the face of the whole earth.', NOW()),
  ('BEZER', 'Deuteronomy 4:43', 'The cities were: Bezer in the wilderness plateau, for the Reubenites; Ramoth in Gilead, for the Gadites; and Golan in Bashan, for the Manassites.', NOW()),
  ('ENDOR', '1 Samuel 28:7', 'Saul then said to his attendants, Find me a woman who is a medium, so I may go and inquire of her. There is one in Endor, they said.', NOW()),
  ('GAZER', '1 Chronicles 14:16', 'So David did as God commanded him, and they struck down the Philistine army, all the way from Gibeon to Gazer.', NOW()),
  ('GOLAN', 'Deuteronomy 4:43', 'Golan in Bashan was one of the cities of refuge, set apart for the Manassites.', NOW()),
  ('HAZOR', 'Joshua 11:10', 'At that time Joshua turned back and captured Hazor and put its king to the sword. Hazor had been the head of all these kingdoms.', NOW()),
  ('HOREB', 'Exodus 17:6', 'I will stand there before you by the rock at Horeb. Strike the rock, and water will come out of it for the people to drink.', NOW()),
  ('JOPPA', 'Jonah 1:3', 'But Jonah ran away from the LORD and headed for Tarshish. He went down to Joppa, where he found a ship bound for that port.', NOW()),
  ('KEDAR', 'Psalm 120:5', 'Woe to me that I dwell in Meshek, that I live among the tents of Kedar!', NOW()),
  ('LYCIA', 'Acts 27:5', 'When we had sailed across the open sea off the coast of Cilicia and Pamphylia, we landed at Myra in Lycia.', NOW()),
  ('MARAH', 'Exodus 15:23', 'When they came to Marah, they could not drink its water because it was bitter. That is why the place is called Marah.', NOW()),
  ('OPHIR', '1 Kings 9:28', 'His men went to Ophir and brought back 420 talents of gold, which they delivered to King Solomon.', NOW()),
  ('RAMAH', 'Jeremiah 31:15', 'A voice is heard in Ramah, mourning and great weeping, Rachel weeping for her children and refusing to be comforted, because they are no more.', NOW()),
  ('SODOM', 'Genesis 19:24', 'Then the LORD rained down burning sulfur on Sodom and Gomorrah — from the LORD out of the heavens.', NOW()),
  ('TABOR', 'Judges 4:6', 'She sent for Barak and said to him, Go, take with you ten thousand men of Naphtali and Zebulun and lead them up to Mount Tabor.', NOW()),
  ('TAMAR', 'Genesis 38:11', 'Judah then said to his daughter-in-law Tamar, Live as a widow in your father''s household until my son Shelah grows up.', NOW()),
  ('TEKOA', 'Amos 1:1', 'The words of Amos, one of the shepherds of Tekoa — the vision he saw concerning Israel two years before the earthquake.', NOW()),
  ('TROAS', 'Acts 16:11', 'From Troas we put out to sea and sailed straight for Samothrace, and the next day we went on to Neapolis.', NOW()),
  ('ZORAH', 'Judges 13:2', 'A certain man of Zorah, named Manoah, from the clan of the Danites, had a wife who was childless, unable to give birth.', NOW()),
  ('ABYSS', 'Revelation 9:1', 'The fifth angel sounded his trumpet, and I saw a star that had fallen from the sky to the earth. The star was given the key to the shaft of the Abyss.', NOW()),
  ('AGONY', 'Luke 22:44', 'And being in agony he prayed more earnestly; and his sweat became like great drops of blood falling down to the ground.', NOW()),
  ('AHAVA', 'Ezra 8:15', 'I assembled them at the canal that flows toward Ahava, and we camped there three days while I checked among the people and the priests.', NOW()),
  ('ALIVE', 'Romans 6:11', 'In the same way, count yourselves dead to sin but alive to God in Christ Jesus.', NOW()),
  ('ALONE', 'Matthew 14:23', 'After he had dismissed them, he went up on a mountainside by himself to pray. Later that night, he was there alone.', NOW()),
  ('ALPHA', 'Revelation 1:8', 'I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.', NOW()),
  ('ALTAR', 'Genesis 8:20', 'Then Noah built an altar to the LORD and, taking some of all the clean animals and clean birds, he sacrificed burnt offerings on it.', NOW()),
  ('AMNON', '2 Samuel 3:2', 'Sons were born to David in Hebron: His firstborn was Amnon the son of Ahinoam of Jezreel.', NOW()),
  ('ARIEL', 'Isaiah 29:1', 'Woe to you, Ariel, Ariel, the city where David settled! Add year to year and let your cycle of festivals go on.', NOW()),
  ('AROMA', '2 Corinthians 2:15', 'For we are to God the pleasing aroma of Christ among those who are being saved and those who are perishing.', NOW()),
  ('AWOKE', 'Genesis 28:16', 'When Jacob awoke from his sleep, he thought, Surely the LORD is in this place, and I was not aware of it.', NOW()),
  ('BARAK', 'Hebrews 11:32', 'And what more shall I say? I do not have time to tell about Gideon, Barak, Samson and Jephthah, about David and Samuel and the prophets.', NOW()),
  ('BARNS', 'Luke 12:18', 'Then he said, This is what I''ll do. I will tear down my barns and build bigger ones, and there I will store my surplus grain.', NOW()),
  ('BASIN', 'John 13:5', 'After that, he poured water into a basin and began to wash his disciples'' feet, drying them with the towel that was wrapped around him.', NOW()),
  ('BERYL', 'Revelation 21:20', 'The fifth sardonyx, the sixth carnelian, the seventh chrysolite, the eighth beryl, the ninth topaz, the tenth turquoise.', NOW()),
  ('BIRDS', 'Matthew 6:26', 'Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them.', NOW()),
  ('BROOK', '1 Kings 17:3', 'Leave here, turn eastward and hide in the Kerith Ravine, east of the Jordan. You will drink from the brook.', NOW()),
  ('BROOD', 'Matthew 23:33', 'You snakes! You brood of vipers! How will you escape being condemned to hell?', NOW()),
  ('CHASE', 'Leviticus 26:8', 'Five of you will chase a hundred, and a hundred of you will chase ten thousand, and your enemies will fall by the sword before you.', NOW()),
  ('CLEFT', 'Exodus 33:22', 'When my glory passes by, I will put you in a cleft in the rock and cover you with my hand until I have passed by.', NOW()),
  ('COALS', 'Romans 12:20', 'If your enemy is hungry, feed him; if he is thirsty, give him something to drink. In doing this, you will heap burning coals on his head.', NOW()),
  ('COVER', 'James 5:20', 'Whoever turns a sinner from the error of their way will save them from death and cover over a multitude of sins.', NOW()),
  ('DEBTS', 'Matthew 6:12', 'And forgive us our debts, as we also have forgiven our debtors.', NOW()),
  ('DEITY', 'Colossians 2:9', 'For in Christ all the fullness of the Deity lives in bodily form.', NOW()),
  ('DEMAS', '2 Timothy 4:10', 'For Demas, because he loved this world, has deserted me and has gone to Thessalonica.', NOW()),
  ('DEVIL', '1 Peter 5:8', 'Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour.', NOW()),
  ('DRAWN', 'Jeremiah 31:3', 'I have loved you with an everlasting love; I have drawn you with unfailing kindness.', NOW()),
  ('DROSS', 'Proverbs 25:4', 'Remove the dross from the silver, and a silversmith can produce a vessel.', NOW()),
  ('DREAM', 'Joel 2:28', 'And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams.', NOW()),
  ('EMPTY', 'Ruth 1:21', 'I went away full, but the LORD has brought me back empty. Why call me Naomi? The LORD has afflicted me; the Almighty has brought misfortune upon me.', NOW()),
  ('ETHAM', 'Exodus 13:20', 'After leaving Sukkoth they camped at Etham on the edge of the desert.', NOW()),
  ('EZION', '1 Kings 9:26', 'King Solomon also built ships at Ezion Geber, which is near Elath in Edom, on the shore of the Red Sea.', NOW()),
  ('FAINT', 'Isaiah 40:31', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.', NOW()),
  ('FALSE', 'Proverbs 19:5', 'A false witness will not go unpunished, and whoever pours out lies will not go free.', NOW()),
  ('FIERY', '1 Peter 4:12', 'Dear friends, do not be surprised at the fiery ordeal that has come on you to test you, as though something strange were happening to you.', NOW()),
  ('FIELD', 'Matthew 13:44', 'The kingdom of heaven is like treasure hidden in a field. When a man found it, he hid it again, and then in his joy went and sold all he had and bought that field.', NOW()),
  ('FLINT', 'Ezekiel 3:9', 'Like the hardest stone, harder than flint, I will make your forehead. Do not be afraid of them or terrified by them.', NOW()),
  ('FLOUR', 'Numbers 28:5', 'Together with a grain offering of one-tenth of an ephah of fine flour mixed with a quarter of a hin of oil from pressed olives.', NOW()),
  ('FLUTE', 'Daniel 3:5', 'As soon as you hear the sound of the horn, flute, zither, lyre, harp, pipe and all kinds of music, you must fall down and worship the image of gold.', NOW()),
  ('FORTY', 'Matthew 4:2', 'After fasting forty days and forty nights, he was hungry.', NOW()),
  ('FRESH', 'Psalm 92:14', 'They will still bear fruit in old age, they will stay fresh and green.', NOW()),
  ('GHOST', 'Acts 2:4', 'And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.', NOW()),
  ('GLOOM', 'Joel 2:2', 'A day of darkness and gloom, a day of clouds and blackness. Like dawn spreading across the mountains a large and mighty army comes.', NOW()),
  ('HADAD', '1 Kings 11:14', 'Then the LORD raised up against Solomon an adversary, Hadad the Edomite, from the royal line of Edom.', NOW()),
  ('HADES', 'Matthew 16:18', 'And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.', NOW()),
  ('HAVEN', 'Psalm 107:30', 'They were glad when it grew calm, and he guided them to their desired haven.', NOW()),
  ('HONEY', 'Exodus 3:8', 'So I have come down to rescue them and to bring them up into a good and spacious land, a land flowing with milk and honey.', NOW()),
  ('HORSE', 'Revelation 19:11', 'I saw heaven standing open and there before me was a white horse, whose rider is called Faithful and True.', NOW()),
  ('IDOLS', 'Psalm 115:4', 'But their idols are silver and gold, made by human hands. They have mouths, but cannot speak, eyes, but cannot see.', NOW()),
  ('INNER', 'Ephesians 3:16', 'I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being.', NOW()),
  ('JEWEL', 'Proverbs 20:15', 'Gold there is, and rubies in abundance, but lips that speak knowledge are a rare jewel.', NOW()),
  ('KEBAR', 'Ezekiel 1:1', 'While I was among the exiles by the Kebar River, the heavens were opened and I saw visions of God.', NOW()),
  ('KINGS', 'Psalm 2:10', 'Therefore, you kings, be wise; be warned, you rulers of the earth.', NOW()),
  ('MOURN', 'Matthew 5:4', 'Blessed are those who mourn, for they will be comforted.', NOW()),
  ('NAKED', 'Genesis 2:25', 'Adam and his wife were both naked, and they felt no shame.', NOW()),
  ('NORTH', 'Ezekiel 1:4', 'I looked, and I saw a windstorm coming out of the north — an immense cloud with flashing lightning and surrounded by brilliant light.', NOW()),
  ('PLAIN', 'Genesis 13:12', 'Abram lived in the land of Canaan, while Lot lived among the cities of the plain and pitched his tents near Sodom.', NOW()),
  ('QUIET', '1 Thessalonians 4:11', 'Make it your ambition to lead a quiet life: You should mind your own business and work with your hands, just as we told you.', NOW()),
  ('RABBI', 'John 1:38', 'Turning around, Jesus saw them following and asked, What do you want? They said, Rabbi — which means Teacher — where are you staying?', NOW()),
  ('REBEL', 'Numbers 14:9', 'Only do not rebel against the LORD. And do not be afraid of the people of the land, because we will devour them.', NOW()),
  ('ROBES', 'Revelation 7:9', 'There before me was a great multitude that no one could count, from every nation, tribe, people and language, standing before the throne. They were wearing white robes.', NOW()),
  ('RUINS', 'Isaiah 61:4', 'They will rebuild the ancient ruins and restore the places long devastated; they will renew the ruined cities that have been devastated for generations.', NOW()),
  ('SHADE', 'Psalm 121:5', 'The LORD watches over you — the LORD is your shade at your right hand.', NOW()),
  ('SHAME', 'Hebrews 12:2', 'For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God.', NOW()),
  ('SHARE', 'Philippians 1:7', 'Whether I am in chains or defending and confirming the gospel, all of you share in God''s grace with me.', NOW()),
  ('SOUTH', 'Job 37:17', 'You who swelter in your clothes when the land lies hushed under the south wind?', NOW()),
  ('STARS', 'Job 38:7', 'When the morning stars sang together and all the angels shouted for joy?', NOW()),
  ('STEAL', 'Exodus 20:15', 'You shall not steal.', NOW()),
  ('THIRD', 'Matthew 16:21', 'Jesus began to explain to his disciples that he must be killed and on the third day be raised to life.', NOW()),
  ('UNDER', 'Psalm 91:4', 'He will cover you with his feathers, and under his wings you will find refuge; his faithfulness will be your shield and rampart.', NOW()),
  ('WAGES', 'Romans 6:23', 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.', NOW()),
  ('YOKED', '2 Corinthians 6:14', 'Do not be yoked together with unbelievers. For what do righteousness and wickedness have in common?', NOW()),
  ('AWAIT', 'Romans 8:23', 'We ourselves, who have the firstfruits of the Spirit, groan inwardly as we eagerly await our adoption to sonship.', NOW()),
  ('BRIDE', 'Revelation 21:2', 'I saw the Holy City, the new Jerusalem, coming down out of heaven from God, prepared as a bride beautifully dressed for her husband.', NOW()),
  ('CHIEF', 'Acts 28:7', 'There was an estate nearby that belonged to Publius, the chief official of the island.', NOW()),
  ('CLOSE', 'Psalm 34:18', 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.', NOW()),
  ('CRIED', 'Psalm 34:6', 'This poor man cried, and the LORD heard him, and saved him out of all his troubles.', NOW()),
  ('DELAY', 'Habakkuk 2:3', 'For still the vision awaits its appointed time; it hastens to the end — it will not lie. If it seems slow, wait for it; it will surely come; it will not delay.', NOW()),
  ('EVERY', 'Philippians 4:19', 'And my God will meet every need of yours according to his riches in glory in Christ Jesus.', NOW()),
  ('EXACT', 'Hebrews 1:3', 'The Son is the radiance of God''s glory and the exact representation of his being.', NOW()),
  ('FLOWS', 'Ezekiel 47:9', 'Swarms of living creatures will live wherever the river flows. There will be large numbers of fish, because this water flows there and makes the salt water fresh.', NOW()),
  ('HARSH', 'Proverbs 15:1', 'A gentle answer turns away wrath, but a harsh word stirs up anger.', NOW()),
  ('LATER', 'John 13:7', 'Jesus replied, You do not realize now what I am doing, but later you will understand.', NOW()),
  ('LIFTS', 'Psalm 3:3', 'But you, LORD, are a shield around me, my glory, the One who lifts my head high.', NOW()),
  ('LOOPS', 'Exodus 26:4', 'Make loops of blue material along the edge of the end curtain in one set, and do the same with the end curtain in the other set.', NOW()),
  ('MAKES', 'Psalm 23:2', 'He makes me lie down in green pastures, he leads me beside quiet waters.', NOW()),
  ('OUGHT', 'Romans 8:26', 'We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.', NOW()),
  ('PLANS', 'Jeremiah 29:11', 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you.', NOW()),
  ('PRIZE', 'Philippians 3:14', 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.', NOW()),
  ('SHONE', 'Luke 2:9', 'An angel of the Lord appeared to them, and the glory of the Lord shone around them, and they were terrified.', NOW()),
  ('SHOWN', 'Micah 6:8', 'He has shown you, O mortal, what is good. And what does the LORD require of you?', NOW()),
  ('SPENT', 'Isaiah 49:4', 'But I said, I have labored in vain; I have spent my strength for nothing at all. Yet what is due me is in the LORD''s hand.', NOW()),
  ('SPOKE', 'Hebrews 1:1', 'In the past God spoke to our ancestors through the prophets at many times and in various ways.', NOW()),
  ('STAND', 'Ephesians 6:13', 'Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground.', NOW()),
  ('STILL', 'Psalm 46:10', 'He says, Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.', NOW()),
  ('SWEET', 'Psalm 119:103', 'How sweet are your words to my taste, sweeter than honey to my mouth!', NOW()),
  ('TASTE', 'Psalm 34:8', 'Taste and see that the LORD is good; blessed is the one who takes refuge in him.', NOW()),
  ('TENDS', 'Isaiah 40:11', 'He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart.', NOW()),
  ('TODAY', 'Hebrews 3:15', 'As has just been said: Today, if you hear his voice, do not harden your hearts.', NOW()),
  ('TURNS', 'Proverbs 15:1', 'A gentle answer turns away wrath, but a harsh word stirs up anger.', NOW()),
  ('BALAK', 'Numbers 22:4', 'So Balak son of Zippor, who was king of Moab at that time, sent messengers to summon Balaam son of Beor.', NOW()),
  ('DINAH', 'Genesis 30:21', 'Some time later she gave birth to a daughter and named her Dinah.', NOW()),
  ('HAMAN', 'Esther 3:5', 'When Haman saw that Mordecai would not kneel down or pay him honor, he was enraged.', NOW()),
  ('JARED', 'Genesis 5:20', 'Altogether, Jared lived a total of 962 years, and then he died.', NOW()),
  ('JORAM', '2 Kings 9:24', 'Then Jehu drew his bow and shot Joram between the shoulders. The arrow pierced his heart and he slumped down in his chariot.', NOW()),
  ('JUNIA', 'Romans 16:7', 'Greet Andronicus and Junia, my fellow Jews who have been in prison with me. They are outstanding among the apostles.', NOW()),
  ('MAGOG', 'Revelation 20:8', 'He will go out to deceive the nations in the four corners of the earth — Gog and Magog — and to gather them for battle.', NOW()),
  ('ORPAH', 'Ruth 1:14', 'At this they wept aloud again. Then Orpah kissed her mother-in-law goodbye, but Ruth clung to her.', NOW()),
  ('PELEG', 'Genesis 10:25', 'Two sons were born to Eber: One was named Peleg, because in his time the earth was divided.', NOW()),
  ('PERGA', 'Acts 13:13', 'From Paphos, Paul and his companions sailed to Perga in Pamphylia, where John left them to return to Jerusalem.', NOW()),
  ('RHODA', 'Acts 12:13', 'Peter knocked at the outer entrance, and a servant named Rhoda came to answer the door.', NOW()),
  ('SELAH', 'Psalm 46:3', 'Though its waters roar and foam and the mountains quake with their surging — Selah.', NOW()),
  ('SHEBA', '1 Kings 10:1', 'When the queen of Sheba heard about the fame of Solomon and his relationship to the LORD, she came to test Solomon with hard questions.', NOW()),
  ('SIDON', 'Matthew 11:21', 'Woe to you, Chorazin! Woe to you, Bethsaida! For if the miracles that were performed in you had been performed in Tyre and Sidon, they would have repented long ago.', NOW()),
  ('TUBAL', 'Ezekiel 38:2', 'Son of man, set your face against Gog, of the land of Magog, the chief prince of Meshek and Tubal; prophesy against him.', NOW()),
  ('UZZAH', '2 Samuel 6:7', 'The LORD''s anger burned against Uzzah because of his irreverent act; therefore God struck him down, and he died there beside the ark of God.', NOW()),
  ('ZELAH', '2 Samuel 21:14', 'They buried the bones of Saul and his son Jonathan in the tomb of Saul''s father Kish, at Zelah in Benjamin.', NOW()),
  ('ZERAH', 'Genesis 38:30', 'Then his brother, who had the scarlet thread on his wrist, came out. And he was named Zerah.', NOW()),
  ('ZENAS', 'Titus 3:13', 'Do everything you can to help Zenas the lawyer and Apollos on their way and see that they have everything they need.', NOW()),
  ('LINUS', '2 Timothy 4:21', 'Do your best to get here before winter. Eubulus greets you, and so do Pudens, Linus, Claudia and all the brothers and sisters.', NOW()),
  ('DEBIR', 'Joshua 10:38', 'Then Joshua and all Israel with him turned around and attacked Debir. They took the city, its king and its villages.', NOW()),
  ('CARMI', 'Numbers 26:6', 'Through Carmi, the Carmite clan.', NOW()),
  ('EPHAH', 'Ruth 2:17', 'So Ruth gleaned in the field until evening. Then she threshed the barley she had gathered, and it amounted to about an ephah.', NOW()),
  ('KENAN', 'Genesis 5:12', 'When Kenan had lived 70 years, he became the father of Mahalalel.', NOW()),
  ('IBZAN', 'Judges 12:8', 'After him, Ibzan of Bethlehem led Israel.', NOW()),
  ('IMMER', 'Nehemiah 7:40', 'The descendants of Immer 1,052.', NOW()),
  ('MAHLI', 'Numbers 3:20', 'The Merarite clans: Mahli and Mushi. These were the Levite clans, listed by their families.', NOW()),
  ('PARAN', 'Habakkuk 3:3', 'God came from Teman, the Holy One from Mount Paran. His glory covered the heavens and his praise filled the earth.', NOW()),
  ('SERAH', 'Numbers 26:46', 'And Asher''s daughter was Serah.', NOW()),
  ('TIMNA', 'Genesis 36:22', 'Lotan''s sister was Timna.', NOW()),
  ('ZAHAM', '2 Chronicles 11:19', 'Who bore him Jeush, Shemariah and Zaham.', NOW()),
  ('ZOBAH', '1 Samuel 14:47', 'After Saul had assumed rule over Israel, he fought against their enemies on every side: Moab, the Ammonites, Edom, the kings of Zobah.', NOW()),
  ('KENAZ', 'Judges 3:9', 'But when they cried out to the LORD, he raised up for them a deliverer, Othniel son of Kenaz, Caleb''s younger brother, who saved them.', NOW()),
  ('NOGAH', '1 Chronicles 3:7', 'Nogah, Nepheg, Japhia.', NOW()),
  ('TIRAS', 'Genesis 10:2', 'The sons of Japheth: Gomer, Magog, Madai, Javan, Tubal, Meshek and Tiras.', NOW()),
  ('SHETH', 'Numbers 24:17', 'A star will come out of Jacob; a scepter will rise out of Israel. He will crush the foreheads of Moab, the skulls of all the people of Sheth.', NOW()),
  ('PURIM', 'Esther 9:26', 'These days were called Purim, from the word pur. Therefore because of everything written in this letter and because of what they had seen and what had happened to them.', NOW()),
  ('SALEM', 'Genesis 14:18', 'Then Melchizedek king of Salem brought out bread and wine. He was priest of God Most High.', NOW()),
  ('SYRIA', 'Luke 2:2', 'This was the first census that took place while Quirinius was governor of Syria.', NOW()),
  ('SILAS', 'Acts 16:25', 'About midnight Paul and Silas were praying and singing hymns to God, and the other prisoners were listening to them.', NOW()),
  ('ASSOS', 'Acts 20:13', 'We went on ahead to the ship and sailed for Assos, where we were going to take Paul aboard.', NOW()),
  ('MYSIA', 'Acts 16:7', 'When they came to the border of Mysia, they tried to enter Bithynia, but the Spirit of Jesus would not allow them to.', NOW()),
  ('ZOHAR', 'Genesis 23:8', 'He said to them, If you are willing to let me bury my dead, then listen to me and intercede with Ephron son of Zohar on my behalf.', NOW()),
  ('LAISH', 'Judges 18:7', 'So the five men left and came to Laish, where they saw that the people were living in safety, like the Sidonians.', NOW()),
  ('ACHOR', 'Joshua 7:26', 'They raised a large pile of rocks over Achan, which remains to this day. Then the LORD turned from his fierce anger. Therefore that place has been called the Valley of Achor ever since.', NOW()),
  ('AGREE', 'Matthew 18:19', 'Again, truly I tell you that if two of you on earth agree about anything they ask for, it will be done for them by my Father in heaven.', NOW()),
  ('ASHES', 'Job 42:6', 'Therefore I despise myself and repent in dust and ashes.', NOW()),
  ('BEARD', 'Ezra 9:3', 'When I heard this, I tore my tunic and cloak, pulled hair from my head and beard and sat down appalled.', NOW()),
  ('BELOW', 'John 8:23', 'But he continued, You are from below; I am from above. You are of this world; I am not of this world.', NOW()),
  ('BOAST', 'Jeremiah 9:23', 'This is what the LORD says: Let not the wise boast of their wisdom or the strong boast of their strength or the rich boast of their riches.', NOW()),
  ('BOOKS', 'Revelation 20:12', 'And I saw the dead, great and small, standing before the throne, and books were opened.', NOW()),
  ('BOWLS', 'Revelation 15:7', 'Then one of the four living creatures gave to the seven angels seven golden bowls filled with the wrath of God.', NOW()),
  ('BURNT', 'Psalm 51:16', 'You do not delight in sacrifice, or I would bring it; you do not take pleasure in burnt offerings.', NOW()),
  ('BURST', 'Job 32:19', 'Inside I am like bottled-up wine, like new wineskins ready to burst.', NOW()),
  ('CARES', '1 Peter 5:7', 'Cast all your anxiety on him because he cares for you.', NOW()),
  ('CHAIN', 'Acts 28:20', 'For this reason I have asked to see you and talk with you. It is because of the hope of Israel that I am bound with this chain.', NOW()),
  ('CHEEK', 'Matthew 5:39', 'But I tell you, do not resist an evil person. If anyone slaps you on the right cheek, turn to them the other cheek also.', NOW()),
  ('CHOKE', 'Mark 4:19', 'But the worries of this life, the deceitfulness of wealth and the desires for other things come in and choke the word, making it unfruitful.', NOW()),
  ('CLAIM', 'John 10:33', 'We are not stoning you for any good work, they replied, but for blasphemy, because you, a mere man, claim to be God.', NOW()),
  ('COAST', 'Acts 27:2', 'We boarded a ship from Adramyttium about to sail for ports along the coast of the province of Asia.', NOW()),
  ('COINS', 'Luke 15:8', 'Or suppose a woman has ten silver coins and loses one. Does she not light a lamp, sweep the house and search carefully until she finds it?', NOW()),
  ('CORDS', 'John 2:15', 'So he made a whip out of cords, and drove all from the temple courts, both sheep and cattle.', NOW()),
  ('DEPTH', 'Romans 8:39', 'Neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.', NOW()),
  ('DIRGE', 'Luke 7:32', 'They are like children sitting in the marketplace and calling out to each other: We played the pipe for you, and you did not dance; we sang a dirge, and you did not cry.', NOW()),
  ('DOORS', 'John 20:19', 'On the evening of that first day of the week, when the disciples were together, with the doors locked for fear of Jewish leaders, Jesus came and stood among them.', NOW()),
  ('EAGER', 'Romans 1:15', 'That is why I am so eager to preach the gospel also to you who are in Rome.', NOW()),
  ('EARLY', 'Mark 16:2', 'Very early on the first day of the week, just after sunrise, they were on their way to the tomb.', NOW()),
  ('ERROR', 'James 5:20', 'Remember this: Whoever turns a sinner from the error of their way will save them from death.', NOW()),
  ('EXALT', 'Psalm 34:3', 'Glorify the LORD with me; let us exalt his name together.', NOW()),
  ('FORDS', 'Joshua 2:7', 'So the men set out in pursuit of the spies on the road that leads to the fords of the Jordan.', NOW()),
  ('FOXES', 'Song of Solomon 2:15', 'Catch for us the foxes, the little foxes that ruin the vineyards, our vineyards that are in bloom.', NOW()),
  ('FROST', 'Job 38:29', 'From whose womb comes the ice? Who gives birth to the frost from the heavens?', NOW()),
  ('GREET', 'Romans 16:16', 'Greet one another with a holy kiss. All the churches of Christ send greetings.', NOW()),
  ('GROPE', 'Job 5:14', 'Darkness comes upon them in the daytime; at noon they grope as in the night.', NOW()),
  ('HASTE', 'Exodus 12:11', 'This is how you are to eat it: with your cloak tucked into your belt, your sandals on your feet and your staff in your hand. Eat it in haste; it is the LORD''s Passover.', NOW()),
  ('HEARD', 'Genesis 3:8', 'Then the man and his wife heard the sound of the LORD God as he was walking in the garden in the cool of the day.', NOW()),
  ('HIRED', 'Luke 15:17', 'When he came to his senses, he said, How many of my father''s hired servants have food to spare, and here I am starving to death!', NOW()),
  ('HORNS', 'Revelation 5:6', 'Then I saw a Lamb, looking as if it had been slain, standing at the center of the throne. He had seven horns and seven eyes.', NOW()),
  ('IVORY', 'Amos 6:4', 'You lie on beds adorned with ivory and lounge on your couches. You dine on choice lambs and fattened calves.', NOW()),
  ('KNOCK', 'Matthew 7:7', 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.', NOW()),
  ('LAUGH', 'Genesis 21:6', 'Sarah said, God has brought me laughter, and everyone who hears about this will laugh with me.', NOW()),
  ('LINEN', 'Revelation 19:8', 'Fine linen, bright and clean, was given her to wear. Fine linen stands for the righteous acts of God''s holy people.', NOW()),
  ('LOOSE', 'Isaiah 58:6', 'Is not this the kind of fasting I have chosen: to loose the chains of injustice and untie the cords of the yoke, to set the oppressed free?', NOW()),
  ('MAKER', 'Job 35:10', 'But no one says, Where is God my Maker, who gives songs in the night?', NOW()),
  ('RAINS', 'Joel 2:23', 'Be glad, people of Zion, rejoice in the LORD your God, for he has given you the autumn rains because he is faithful.', NOW()),
  ('REEDS', 'Exodus 2:3', 'But when she could hide him no longer, she got a papyrus basket for him and coated it with tar and pitch. Then she placed the child in it and put it among the reeds along the bank of the Nile.', NOW()),
  ('SEVEN', 'Revelation 1:20', 'The mystery of the seven stars that you saw in my right hand and of the seven golden lampstands is this: The seven stars are the angels of the seven churches.', NOW()),
  ('SHOOT', 'Isaiah 11:1', 'A shoot will come up from the stump of Jesse; from his roots a Branch will bear fruit.', NOW()),
  ('SHORE', 'John 21:4', 'Early in the morning, Jesus stood on the shore, but the disciples did not realize that it was Jesus.', NOW()),
  ('SIEVE', 'Amos 9:9', 'For I will give the command, and I will shake the people of Israel among all the nations as grain is shaken in a sieve.', NOW()),
  ('SLAIN', 'Revelation 5:12', 'Worthy is the Lamb, who was slain, to receive power and wealth and wisdom and strength and honor and glory and praise!', NOW()),
  ('SMOKE', 'Exodus 19:18', 'Mount Sinai was covered with smoke, because the LORD descended on it in fire. The smoke billowed up from it like smoke from a furnace.', NOW()),
  ('SPIES', 'Joshua 2:1', 'Then Joshua son of Nun secretly sent two spies from Shittim. Go, look over the land, he said, especially Jericho.', NOW()),
  ('STUMP', 'Isaiah 6:13', 'But as the terebinth and oak leave stumps when they are cut down, so the holy seed will be the stump in the land.', NOW()),
  ('SWORE', 'Hebrews 6:13', 'When God made his promise to Abraham, since there was no one greater for him to swear by, he swore by himself.', NOW()),
  ('TENTH', 'Genesis 14:20', 'And praise be to God Most High, who delivered your enemies into your hand. Then Abram gave him a tenth of everything.', NOW()),
  ('THIEF', 'John 10:10', 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.', NOW()),
  ('TOMBS', 'Matthew 27:53', 'They came out of the tombs after Jesus'' resurrection and went into the holy city and appeared to many people.', NOW()),
  ('TRULY', 'John 3:3', 'Jesus replied, Very truly I tell you, no one can see the kingdom of God unless they are born again.', NOW()),
  ('WAITS', 'Psalm 130:5', 'I wait for the LORD, my whole being waits, and in his word I put my hope.', NOW()),
  ('WOVEN', 'Psalm 139:15', 'My frame was not hidden from you when I was made in the secret place, when I was woven together in the depths of the earth.', NOW()),
  ('CAVES', 'Hebrews 11:38', 'The world was not worthy of them. They wandered in deserts and mountains, living in caves and in holes in the ground.', NOW()),
  ('CURSE', 'Galatians 3:13', 'Christ redeemed us from the curse of the law by becoming a curse for us.', NOW()),
  ('DECAY', 'Acts 2:31', 'Seeing what was to come, he spoke of the resurrection of the Messiah, that he was not abandoned to the realm of the dead, nor did his body see decay.', NOW()),
  ('DIMLY', '1 Corinthians 13:12', 'For now we see only a reflection as in a mirror; we see dimly. But then we shall see face to face.', NOW()),
  ('EQUIP', 'Hebrews 13:21', 'Equip you with everything good for doing his will, and may he work in us what is pleasing to him.', NOW()),
  ('FAVOR', 'Luke 2:52', 'And Jesus grew in wisdom and stature, and in favor with God and man.', NOW()),
  ('GREED', 'Colossians 3:5', 'Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.', NOW()),
  ('HEDGE', 'Job 1:10', 'Have you not put a hedge around him and his household and everything he has?', NOW()),
  ('JEERS', 'Hebrews 11:36', 'Some faced jeers and flogging, and even chains and imprisonment.', NOW()),
  ('MEANT', 'John 11:13', 'Jesus had been speaking of his death, but his disciples thought he meant natural sleep.', NOW()),
  ('OFTEN', 'Luke 13:34', 'Jerusalem, Jerusalem, you who kill the prophets and stone those sent to you, how often I have longed to gather your children together.', NOW()),
  ('PLACE', 'Revelation 21:3', 'And I heard a loud voice from the throne saying, Look! God''s dwelling place is now among the people.', NOW()),
  ('PLANK', 'Matthew 7:5', 'You hypocrite, first take the plank out of your own eye, and then you will see clearly to remove the speck from your brother''s eye.', NOW()),
  ('SEERS', 'Isaiah 30:10', 'They say to the seers, See no more visions! and to the prophets, Give us no more visions of what is right!', NOW()),
  ('TENTS', 'Psalm 84:10', 'Better is one day in your courts than a thousand elsewhere; I would rather be a doorkeeper in the house of my God than dwell in the tents of the wicked.', NOW()),
  ('THEME', 'Psalm 45:1', 'My heart is stirred by a noble theme as I recite my verses for the king; my tongue is the pen of a skillful writer.', NOW()),
  ('WEEDS', 'Matthew 13:25', 'But while everyone was sleeping, his enemy came and sowed weeds among the wheat, and went away.', NOW()),
  ('YEAST', 'Matthew 13:33', 'The kingdom of heaven is like yeast that a woman took and mixed into about sixty pounds of flour until it worked all through the dough.', NOW())
ON CONFLICT (word) DO NOTHING;
